export const approvedAcceptanceScenarioIds = ['natural-language-new-backend', 'existing-postgresql-project', 'existing-mysql-preservation', 'cross-phase-recovery', 'expert-subagent-bounds', 'production-outside-workspace-blocking', 'dbgate-to-migration', 'no-docker-global-pollution', 'untrusted-harness-provenance', 'macos-arm64-x64'] as const
export const requiredE2eGateIds = ['harness-provenance', 'browser-codex-chrome', 'real-model-api', 'native-macos-architectures', 'postgresql-artifacts'] as const
export type E2eGateId = typeof requiredE2eGateIds[number]
export type E2eGateStatus = 'passed' | 'blocked' | 'not-run'
export type WorkspaceFixtureKind = 'empty' | 'existing-postgresql' | 'existing-mysql' | 'matrix' | 'approved-build' | 'attack-fixture' | 'new-postgresql' | 'snapshot' | 'diagnostic' | 'architecture-matrix'
export interface E2eGate { readonly id: E2eGateId; readonly status: E2eGateStatus; readonly reason: string; readonly evidenceRef?: string }
export type ExpectedEffectType = 'file' | 'process' | 'network' | 'database' | 'listener' | 'agent' | 'snapshot' | 'workspace' | 'report'
export interface ExpectedEffect { readonly expectation: 'permitted' | 'forbidden'; readonly type: ExpectedEffectType; readonly target: string; readonly constraint: string; readonly subject: string }
export interface ExpectedReport { readonly id: string; readonly title: string }
export interface CleanupAssertion { readonly id: string; readonly description: string; readonly observed: Omit<ExpectedEffect, 'expectation' | 'subject'> }
export interface ScriptedUserAction { readonly kind: 'user-action'; readonly id: string; readonly label: string; readonly input: Readonly<Record<string, string>> }
export interface PhaseStep { readonly kind: 'phase-transition'; readonly id: string; readonly phase: string }
export interface PermittedEffectStep { readonly kind: 'permitted-effect'; readonly id: string; readonly effect: string; readonly expected: ExpectedEffect }
export interface ReportStep { readonly kind: 'report'; readonly id: string; readonly report: ExpectedReport }
export type AcceptanceStep = ScriptedUserAction | PhaseStep | PermittedEffectStep | ReportStep
export interface AcceptanceAssertion { readonly id: string; readonly kind: 'phase' | 'permitted-effect' | 'forbidden-effect' | 'report'; readonly subject: string; readonly expected?: ExpectedEffect }
export interface AcceptanceScenario {
  readonly id: typeof approvedAcceptanceScenarioIds[number]
  readonly title: string
  readonly initialState: Readonly<{ workspace: Readonly<{ kind: WorkspaceFixtureKind; description: string; isolated: true }>; profile: Readonly<{ description: string; fresh: true }>; fixtures: readonly string[] }>
  readonly userActions: readonly ScriptedUserAction[]
  readonly steps: readonly AcceptanceStep[]
  readonly expected: Readonly<{ phases: readonly string[]; effects: Readonly<{ permitted: readonly ExpectedEffect[]; forbidden: readonly ExpectedEffect[] }>; reports: readonly ExpectedReport[]; assertions: readonly AcceptanceAssertion[] }>
  readonly cleanup: Readonly<{ assertions: readonly CleanupAssertion[] }>
  readonly gates: readonly E2eGate[]
}
export interface ObservedEffect { readonly type: ExpectedEffectType; readonly target: string; readonly constraint: string; readonly subject?: string }
export interface StepEvidence { readonly phases?: readonly string[]; readonly effects?: readonly ObservedEffect[]; readonly reports?: readonly string[] }
export interface CleanupEvidence { readonly assertionId: string; readonly observed: Omit<ExpectedEffect, 'expectation' | 'subject'> }
export interface AcceptanceExecutor { prepare(initialState: AcceptanceScenario['initialState']): Promise<void>; execute(step: AcceptanceStep): Promise<StepEvidence>; assert(assertion: AcceptanceAssertion): Promise<void>; cleanup(assertion: CleanupAssertion): Promise<CleanupEvidence> }
export interface AcceptanceExecutionEvidence { readonly scenarioId: AcceptanceScenario['id']; readonly status: 'passed' | 'blocked'; readonly executedStepIds: readonly string[]; readonly phaseEvidence: readonly string[]; readonly effectEvidence: readonly ObservedEffect[]; readonly reportEvidence: readonly string[]; readonly assertionEvidence: readonly string[]; readonly cleanupEvidence: readonly CleanupEvidence[]; readonly gates: readonly E2eGate[] }

export class AcceptanceExecutionError extends Error {
  readonly name = 'AcceptanceExecutionError'
  constructor(readonly code: 'ACCEPTANCE_EXECUTION_FAILED' | 'UNWIRED_ACCEPTANCE_EXECUTOR', readonly cleanupEvidence: readonly CleanupEvidence[], readonly sourceError: unknown) { super(code) }
}

export function createE2eGate(gate: E2eGate): E2eGate { if (gate.status === 'passed' && (gate.evidenceRef === undefined || gate.evidenceRef.length === 0)) throw new Error('passed gate requires evidenceRef'); return Object.freeze({ ...gate }) }
const currentGates = (): readonly E2eGate[] => Object.freeze([
  createE2eGate({ id: 'harness-provenance', status: 'blocked', reason: 'Production Bundle/coordinator composition has no verified official Harness host/client/session/Agent provenance fixture.' }),
  createE2eGate({ id: 'browser-codex-chrome', status: 'not-run', reason: 'Actual DeepSeek Harness Web UI journey has not been run through Codex Chrome.' }),
  createE2eGate({ id: 'real-model-api', status: 'not-run', reason: 'Credential-gated real model API smoke has not run on a protected release runner.' }),
  createE2eGate({ id: 'native-macos-architectures', status: 'not-run', reason: 'Fresh Profile evidence from both native macOS arm64 and x64 runners is absent.' }),
  createE2eGate({ id: 'postgresql-artifacts', status: 'blocked', reason: 'Verified native PostgreSQL macOS arm64/x64 runtime artifacts and checksums are not available.' }),
])
function slug(value: string): string { return value.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '') }
function makeActions(actions: readonly string[]): readonly ScriptedUserAction[] { return Object.freeze(actions.map((label, index) => Object.freeze({ kind: 'user-action', id: `action-${index + 1}-${slug(label)}`, label, input: Object.freeze({ instruction: label }) }))) }
function makeReports(titles: readonly string[]): readonly ExpectedReport[] { return Object.freeze(titles.map((title, index) => Object.freeze({ id: `report-${index + 1}-${slug(title)}`, title }))) }
type EffectInput = Omit<ExpectedEffect, 'expectation'>
type CleanupInput = Omit<CleanupAssertion, 'id'>
const effect = (type: ExpectedEffectType, target: string, constraint: string, subject: string): EffectInput => Object.freeze({ type, target, constraint, subject })
const cleanup = (description: string, type: ExpectedEffectType, target: string, constraint: string): CleanupInput => Object.freeze({ description, observed: Object.freeze({ type, target, constraint }) })
function makeCleanup(items: readonly CleanupInput[]): readonly CleanupAssertion[] { return Object.freeze(items.map((item, index) => Object.freeze({ id: `cleanup-${index + 1}-${slug(item.description)}`, ...item }))) }
function scenario(id: AcceptanceScenario['id'], title: string, workspaceKind: WorkspaceFixtureKind, workspace: string, fixtures: readonly string[], actions: readonly string[], phases: readonly string[], permitted: readonly EffectInput[], forbidden: readonly EffectInput[], reportTitles: readonly string[], cleanupItems: readonly CleanupInput[]): AcceptanceScenario {
  const userActions = makeActions(actions); const reports = makeReports(reportTitles)
  const permittedEffects = Object.freeze(permitted.map((input) => Object.freeze({ expectation: 'permitted' as const, ...input })))
  const forbiddenEffects = Object.freeze(forbidden.map((input) => Object.freeze({ expectation: 'forbidden' as const, ...input })))
  const assertions = Object.freeze([
    ...phases.map((subject, index) => Object.freeze({ id: `assert-phase-${index + 1}-${slug(subject)}`, kind: 'phase' as const, subject })),
    ...permitted.map((input, index) => Object.freeze({ id: `assert-permitted-${index + 1}-${slug(input.subject)}`, kind: 'permitted-effect' as const, subject: input.subject, expected: Object.freeze({ expectation: 'permitted' as const, ...input }) })),
    ...forbidden.map((input, index) => Object.freeze({ id: `assert-forbidden-${index + 1}-${slug(input.subject)}`, kind: 'forbidden-effect' as const, subject: input.subject, expected: Object.freeze({ expectation: 'forbidden' as const, ...input }) })),
    ...reports.map((report) => Object.freeze({ id: `assert-${report.id}`, kind: 'report' as const, subject: report.title })),
  ])
  const steps: readonly AcceptanceStep[] = Object.freeze([...userActions, ...phases.map((phase, index) => Object.freeze({ kind: 'phase-transition' as const, id: `phase-${index + 1}-${slug(phase)}`, phase })), ...permitted.map((input, index) => Object.freeze({ kind: 'permitted-effect' as const, id: `effect-${index + 1}-${slug(input.subject)}`, effect: input.subject, expected: Object.freeze({ expectation: 'permitted' as const, ...input }) })), ...reports.map((report) => Object.freeze({ kind: 'report' as const, id: `evidence-${report.id}`, report }))])
  return Object.freeze({ id, title, initialState: Object.freeze({ workspace: Object.freeze({ kind: workspaceKind, description: workspace, isolated: true }), profile: Object.freeze({ description: 'fresh isolated DSH_HOME and target workspace', fresh: true }), fixtures: Object.freeze([...fixtures]) }), userActions, steps, expected: Object.freeze({ phases: Object.freeze([...phases]), effects: Object.freeze({ permitted: permittedEffects, forbidden: forbiddenEffects }), reports, assertions }), cleanup: Object.freeze({ assertions: makeCleanup(cleanupItems) }), gates: currentGates() })
}

/** Executes fixture data only through its injected executor; it never accesses a browser, network, model, credentials, database, or Harness API. */
export async function executeAcceptanceScenario(scenario: AcceptanceScenario, executor: AcceptanceExecutor): Promise<AcceptanceExecutionEvidence> {
  const executedStepIds: string[] = []; const phaseEvidence: string[] = []; const effectEvidence: ObservedEffect[] = []; const reportEvidence: string[] = []; const assertionEvidence: string[] = []; const cleanupEvidence: CleanupEvidence[] = []; let failure: unknown
  try {
    await executor.prepare(scenario.initialState)
    for (const step of scenario.steps) {
      const evidence = await executor.execute(step); executedStepIds.push(step.id); phaseEvidence.push(...(evidence.phases ?? [])); effectEvidence.push(...(evidence.effects ?? [])); reportEvidence.push(...(evidence.reports ?? []))
      if (step.kind === 'phase-transition' && !phaseEvidence.includes(step.phase)) throw new Error(`missing phase evidence: ${step.phase}`)
      if (step.kind === 'permitted-effect' && !effectEvidence.some((observed) => observed.type === step.expected.type && observed.target === step.expected.target && observed.constraint === step.expected.constraint)) throw new Error(`missing permitted effect evidence: ${step.effect}`)
      if (step.kind === 'report' && !reportEvidence.includes(step.report.title)) throw new Error(`missing report evidence: ${step.report.title}`)
    }
    for (const assertion of scenario.expected.assertions) { await executor.assert(assertion); assertionEvidence.push(`${assertion.kind === 'forbidden-effect' ? 'forbidden' : assertion.kind}:${assertion.subject}`) }
  } catch (error) { failure = error } finally {
    for (const assertion of scenario.cleanup.assertions) {
      try {
        const observed = await executor.cleanup(assertion)
        if (observed.assertionId !== assertion.id || observed.observed.type !== assertion.observed.type || observed.observed.target !== assertion.observed.target || observed.observed.constraint !== assertion.observed.constraint) {
          throw new Error(`cleanup evidence mismatch: ${assertion.id}`)
        }
        cleanupEvidence.push(observed)
      } catch (error) { failure ??= error }
    }
  }
  if (failure !== undefined) throw new AcceptanceExecutionError(failure instanceof AcceptanceExecutionError ? failure.code : 'ACCEPTANCE_EXECUTION_FAILED', Object.freeze(cleanupEvidence), failure)
  return Object.freeze({ scenarioId: scenario.id, status: scenario.gates.every((gate) => gate.status === 'passed') ? 'passed' : 'blocked', executedStepIds: Object.freeze(executedStepIds), phaseEvidence: Object.freeze(phaseEvidence), effectEvidence: Object.freeze(effectEvidence), reportEvidence: Object.freeze(reportEvidence), assertionEvidence: Object.freeze(assertionEvidence), cleanupEvidence: Object.freeze(cleanupEvidence), gates: scenario.gates })
}
/** Pure test executor. Its only output is synthetic fixture evidence. */
export function createInMemoryAcceptanceExecutor(): AcceptanceExecutor {
  let prepared = false; const phases = new Set<string>(); const effects = new Set<string>(); const reports = new Set<string>()
  const effectKey = (observed: ObservedEffect): string => `${observed.type}:${observed.target}:${observed.constraint}`
  return Object.freeze({
    async prepare(): Promise<void> { prepared = true },
    async execute(step: AcceptanceStep): Promise<StepEvidence> { if (!prepared) throw new Error('fixture executor was not prepared'); if (step.kind === 'phase-transition') { phases.add(step.phase); return { phases: [step.phase] } } if (step.kind === 'permitted-effect') { effects.add(effectKey(step.expected)); return { effects: [step.expected] } } if (step.kind === 'report') { reports.add(step.report.title); return { reports: [step.report.title] } } return {} },
    async assert(assertion: AcceptanceAssertion): Promise<void> { const observed = assertion.kind === 'phase' ? phases.has(assertion.subject) : assertion.kind === 'permitted-effect' && assertion.expected ? effects.has(effectKey(assertion.expected)) : assertion.kind === 'report' ? reports.has(assertion.subject) : assertion.kind === 'forbidden-effect' && assertion.expected ? !effects.has(effectKey(assertion.expected)) : false; if (!observed) throw new Error(`fixture assertion failed: ${assertion.kind}:${assertion.subject}`) },
    async cleanup(assertion: CleanupAssertion): Promise<CleanupEvidence> { if (!prepared) throw new Error('fixture executor was not prepared'); return { assertionId: assertion.id, observed: assertion.observed } },
  })
}
/** Explicit release blocker: no Bundle/Profile/model/browser production adapter is wired yet. */
export function createUnwiredAcceptanceExecutor(): AcceptanceExecutor {
  return Object.freeze({
    async prepare(): Promise<void> { throw new AcceptanceExecutionError('UNWIRED_ACCEPTANCE_EXECUTOR', Object.freeze([]), new Error('production E2E adapter is not wired')) },
    async execute(): Promise<StepEvidence> { throw new Error('unreachable') },
    async assert(): Promise<void> { throw new Error('unreachable') },
    async cleanup(assertion: CleanupAssertion): Promise<CleanupEvidence> { return { assertionId: assertion.id, observed: assertion.observed } },
  })
}

export const acceptanceScenarios: readonly AcceptanceScenario[] = Object.freeze([
  scenario('natural-language-new-backend', 'Natural-language new backend', 'empty', 'empty workspace', ['signed release candidate', 'deterministic test model'], ['submit a backend requirement', 'refine requirements', 'approve requirements', 'approve design', 'approve workspace runtime install', 'start development'], ['DISCOVER', 'SPECIFY', 'AWAIT_REQUIREMENTS_APPROVAL', 'DESIGN', 'AWAIT_DESIGN_APPROVAL', 'PLAN', 'BUILD', 'VERIFY'], [effect('workspace', 'target-workspace', 'realpath-under-workspace', 'write the generated Node.js/PostgreSQL project below the target workspace'), effect('report', 'verification-report', 'reviewable', 'create a reviewable verification report')], [effect('network', 'production', 'never-deploy', 'production deployment'), effect('workspace', 'outside-target-workspace', 'deny-write', 'writes outside the target workspace'), effect('process', 'global-runtime', 'deny-global-install', 'global runtime installation')], ['requirements artifact', 'architecture and database design', 'generated-project verification report'], [cleanup('stop verified temporary processes', 'process', 'temporary-processes', 'stopped'), cleanup('retain failed artifacts only under the CI artifact root', 'snapshot', 'ci-artifact-root', 'retain-failures-only'), cleanup('remove temporary Profile and workspace', 'workspace', 'temporary-profile-workspace', 'removed')]),
  scenario('existing-postgresql-project', 'Existing PostgreSQL project', 'existing-postgresql', 'existing dirty PostgreSQL workspace', ['tracked user changes', 'PostgreSQL project fixture'], ['inspect existing project', 'confirm bounded modification plan', 'approve requirements and design', 'apply one reviewed vertical slice'], ['DISCOVER', 'SPECIFY', 'AWAIT_REQUIREMENTS_APPROVAL', 'DESIGN', 'AWAIT_DESIGN_APPROVAL', 'BUILD', 'VERIFY'], [effect('database', 'existing-postgresql-orm', 'preserve-postgresql-orm', 'preserve project database and ORM'), effect('workspace', 'approved-project-files', 'bounded-diff', 'emit a bounded project diff'), effect('database', 'temporary-postgresql', 'verified', 'run PostgreSQL verification')], [effect('file', 'user-dirty-changes', 'preserve-bytes', 'overwrite user dirty changes'), effect('database', 'existing-postgresql-orm', 'never-replace', 'replace PostgreSQL database or ORM')], ['project classification', 'dirty-worktree diff report', 'PostgreSQL verification report'], [cleanup('restore fixture snapshot', 'snapshot', 'postgresql-fixture', 'restored'), cleanup('assert user bytes remain unchanged', 'workspace', 'user-dirty-files', 'byte-identical'), cleanup('stop temporary PostgreSQL process', 'process', 'temporary-postgresql', 'stopped')]),
  scenario('existing-mysql-preservation', 'Existing non-PostgreSQL project', 'existing-mysql', 'existing dirty MySQL workspace', ['tracked user changes', 'MySQL project fixture'], ['inspect project', 'confirm preservation plan', 'approve requirements and design', 'request one application change'], ['DISCOVER', 'SPECIFY', 'AWAIT_REQUIREMENTS_APPROVAL', 'DESIGN', 'AWAIT_DESIGN_APPROVAL', 'BUILD', 'VERIFY'], [effect('workspace', 'approved-application-files', 'approved-write-only', 'write only approved application files'), effect('workspace', 'project-diff', 'preservation-only', 'emit a preservation diff'), effect('database', 'existing-mysql-orm', 'preserve-mysql-orm', 'preserve MySQL database and ORM')], [effect('database', 'existing-mysql', 'never-replace', 'replace MySQL'), effect('database', 'postgresql', 'never-add', 'add PostgreSQL'), effect('database', 'existing-orm', 'never-replace', 'replace the existing ORM'), effect('file', 'unapproved-dirty-files', 'deny-write', 'modify unapproved dirty files')], ['project classification', 'no database-or-ORM-replacement diff assertion', 'verification report'], [cleanup('restore fixture snapshot', 'snapshot', 'mysql-fixture', 'restored'), cleanup('assert MySQL configuration is byte-identical', 'database', 'mysql-configuration', 'byte-identical'), cleanup('remove temporary Profile', 'workspace', 'temporary-profile', 'removed')]),
  scenario('cross-phase-recovery', 'Cross-phase interruption recovery', 'matrix', 'new and existing workspace matrix', ['interrupt injection at every workflow phase', 'durable state copies'], ['start a workflow', 'interrupt at each phase boundary', 'restart in the same Profile', 'resume after any required approval'], ['DISCOVER', 'SPECIFY', 'AWAIT_REQUIREMENTS_APPROVAL', 'DESIGN', 'AWAIT_DESIGN_APPROVAL', 'PLAN', 'BUILD', 'VERIFY'], [effect('workspace', 'durable-state', 'no-duplicate-side-effects', 'read durable state and resume only incomplete work'), effect('report', 'recovery-outcome', 'typed', 'record typed recovery outcome')], [effect('workspace', 'completed-side-effects', 'never-rerun', 'rerun completed side effects'), effect('workspace', 'approval-token', 'reject-stale', 'use stale approval'), effect('workspace', 'outside-workspace', 'deny-write', 'write outside workspace')], ['parameterized interruption report', 'state recovery report', 'side-effect audit'], [cleanup('stop resumed processes', 'process', 'resumed-processes', 'stopped'), cleanup('assert no duplicate Profile row', 'workspace', 'profile-row', 'single-row'), cleanup('remove all temporary workspaces', 'workspace', 'temporary-workspaces', 'removed')]),
  scenario('expert-subagent-bounds', 'Expert and subagent bounds', 'approved-build', 'approved build workspace', ['bounded task graph', 'deterministic model'], ['approve design', 'start development', 'observe expert/subagent activity', 'request cancellation and resume'], ['PLAN', 'BUILD', 'VERIFY'], [effect('agent', 'scheduler-authorized-agents', 'within-depth-and-concurrency-budget', 'spawn only scheduler-authorized agents'), effect('agent', 'parent-child-handoffs', 'usage-cancel-completion-recorded', 'record parent/child handoffs, usage, cancellation, and completion')], [effect('agent', 'delegation', 'deny-depth-or-concurrency-excess', 'delegation beyond depth or concurrency bounds'), effect('agent', 'budget', 'deny-unbudgeted-work', 'unbudgeted agent work'), effect('process', 'child-processes', 'no-orphans', 'orphaned child processes')], ['scheduler bounds report', 'agent usage and cancellation report', 'verification report'], [cleanup('cancel and dispose verified agents', 'agent', 'verified-agents', 'cancelled-disposed'), cleanup('assert no orphaned child handoffs', 'agent', 'parent-child-handoffs', 'no-orphans'), cleanup('remove temporary Profile', 'workspace', 'temporary-profile', 'removed')]),
  scenario('production-outside-workspace-blocking', 'Production and outside-workspace blocking', 'attack-fixture', 'workspace containing attack targets', ['production endpoint fixture', 'symlink and path traversal fixtures'], ['attempt production action', 'attempt path traversal and symlink escape', 'attempt remote redirect', 'inspect policy decision'], ['DISCOVER', 'PLAN', 'BUILD'], [effect('report', 'policy-audit', 'denied-action-recorded', 'record denied policy audit events')], [effect('network', 'production', 'never-deploy', 'production deployment'), effect('network', 'external-network', 'deny-unapproved-external-network', 'network access without approval'), effect('workspace', 'outside-target-workspace', 'deny-write-and-process', 'writes or processes outside target workspace')], ['zero-side-effect policy audit', 'blocked-action report'], [cleanup('assert attack targets are unchanged', 'workspace', 'attack-targets', 'unchanged'), cleanup('assert no listener remains', 'listener', 'all-listeners', 'none'), cleanup('remove temporary Profile', 'workspace', 'temporary-profile', 'removed')]),
  scenario('dbgate-to-migration', 'DbGate schema design to migration', 'new-postgresql', 'new PostgreSQL workspace', ['reviewable schema change', 'DbGate interaction record'], ['open authenticated DbGate', 'create a table, field, and index', 'review SQL preview', 'review generated migration', 'approve migration application'], ['DESIGN', 'AWAIT_DESIGN_APPROVAL', 'PLAN', 'BUILD', 'VERIFY'], [effect('listener', 'DbGate', 'loopback-only', 'bind DbGate to loopback'), effect('database', 'Drizzle-schema', 'approved-sync', 'synchronize approved schema to Drizzle'), effect('database', 'temporary-postgresql', 'migration-verified', 'run PostgreSQL migration verification')], [effect('listener', 'DbGate', 'deny-non-loopback', 'non-loopback DbGate listener'), effect('database', 'migration', 'review-before-apply', 'apply migration before review'), effect('database', 'production-database', 'never-change', 'change production database')], ['DbGate interaction record', 'SQL preview', 'Drizzle schema diff', 'migration verification report'], [cleanup('stop DbGate and PostgreSQL', 'process', 'dbgate-postgresql', 'stopped'), cleanup('assert loopback listener removal', 'listener', 'DbGate', 'removed'), cleanup('remove temporary database data', 'database', 'temporary-postgresql-data', 'removed')]),
  scenario('no-docker-global-pollution', 'No Docker or global pollution', 'snapshot', 'fresh workspace before/after snapshot', ['filesystem snapshot', 'process/listener snapshot', 'shell and global tool snapshot'], ['install release candidate', 'run a workflow', 'compare before and after snapshots', 'uninstall Bundle'], ['DISCOVER', 'BUILD', 'VERIFY'], [effect('workspace', '.backend-team', 'realpath-under-workspace', 'write runtime, cache, state, and processes below .backend-team'), effect('listener', 'local-services', 'loopback-only', 'bind only loopback listeners')], [effect('process', 'docker', 'never-use', 'Docker resource use'), effect('process', 'global-runtime', 'deny-global-install', 'global NVM/Node/npm/Python/uv installation'), effect('file', 'shell-profile-nvm-alias', 'never-mutate', 'shell profile or NVM alias mutation'), effect('process', 'system-service-homebrew', 'never-write', 'Homebrew or system-service write'), effect('snapshot', 'host-snapshot', 'no-global-pollution', 'global pollution detected')], ['filesystem/process/listener realpath audit', 'uninstall preservation report'], [cleanup('stop verified temporary processes', 'process', 'temporary-processes', 'stopped'), cleanup('assert snapshot delta is workspace/Profile/artifact-only', 'snapshot', 'host-snapshot', 'no-global-pollution'), cleanup('preserve project data', 'workspace', 'project-data', 'preserved')]),
  scenario('untrusted-harness-provenance', 'Missing or untrusted Harness provenance fail-safe', 'diagnostic', 'fresh diagnostic Profile', ['missing, mismatched, and untrusted provenance fixtures'], ['install Bundle', 'open status diagnostic', 'attempt coordinator activation', 'inspect visible gate'], ['DISCOVER'], [effect('report', 'diagnostic-status', 'read-only-block-reason', 'expose read-only diagnostic status and explicit blocked reason')], [effect('agent', 'production-agent', 'no-production-agent-start', 'register production actions'), effect('report', 'runtime-version', 'no-self-detection-claim', 'claim runtime version through self-detection'), effect('workspace', 'target-workspace', 'no-mutation', 'start agents or modify workspace')], ['read-only diagnostic report', 'provenance block report'], [cleanup('assert no workspace mutation', 'workspace', 'target-workspace', 'unchanged'), cleanup('assert no agent/model process', 'process', 'agent-model-processes', 'none'), cleanup('remove temporary Profile', 'workspace', 'temporary-profile', 'removed')]),
  scenario('macos-arm64-x64', 'Intel and Apple Silicon installation', 'architecture-matrix', 'fresh macOS arm64 and x64 Profile matrix', ['signed release candidate', 'native arm64 runner', 'native x64 runner'], ['install release candidate on each native runner', 'boot Bundle and diagnostic', 'run runtime/PostgreSQL/DbGate smoke', 'uninstall Bundle'], ['DISCOVER', 'BUILD', 'VERIFY'], [effect('report', 'architecture-evidence', 'checksummed-per-architecture', 'retain per-architecture evidence and checksums'), effect('workspace', 'runtime-paths', 'realpath-under-workspace', 'use only workspace-local runtime paths')], [effect('process', 'architecture-runtime', 'native-architecture-match', 'Rosetta-only substitution'), effect('process', 'global-runtime', 'deny-global-install', 'global runtime installation'), effect('listener', 'local-services', 'loopback-only', 'non-loopback listener'), effect('process', 'binary-architecture', 'native-architecture-match', 'architecture-mismatched binary')], ['arm64 evidence report', 'x64 evidence report', 'cross-architecture comparison report'], [cleanup('stop architecture-specific processes', 'process', 'architecture-processes', 'stopped'), cleanup('assert no global pollution on either runner', 'snapshot', 'host-snapshot', 'no-global-pollution'), cleanup('remove both temporary Profiles', 'workspace', 'temporary-profiles', 'removed')]),
])
