export { BaselineRunner } from './baseline-runner.js'
export { compareResults, statusIsFailure } from './result-comparator.js'
export type { ResultComparison } from './result-comparator.js'
export { allRequirementsPassed, buildRequirementEvidence, hasBlockedRequirement } from './requirement-evidence.js'
export type { RequirementEvidence, RequirementStatus, RequirementTrace, RequirementTraceEntry } from './requirement-evidence.js'
export { VerificationCommandRunner } from './verification-command.js'
export type { CommandCapture, VerificationCommand, VerificationCommandRunnerOptions, VerificationPurpose, VerificationStatus } from './verification-command.js'
export { VerificationEngine } from './verification-engine.js'
export type { VerificationEngineOptions, VerificationReport, VerificationRunInput } from './verification-engine.js'
export { projectVerificationCommands, runProjectVerification } from './project-verification.js'
export type { ProjectScriptManifest, ProjectVerificationCommandInput, ProjectVerificationResult, ProjectVerificationRunInput } from './project-verification.js'
export { AuthorizationReview } from './authorization-tests.js'
export type { AuthorizationEvidence, AuthorizationFinding, ProtectedOperation } from './authorization-tests.js'
export { ProductionTargetDetector, SecurityReview } from './security-review.js'
export type { DependencySecurityFinding, ProductionTarget, SecurityReviewFinding, SecurityReviewInput, SecurityReviewReport } from './security-review.js'
export { SecretScanner, scanSecrets } from './secret-scan.js'
export type { SecretFinding, SecretFindingSeverity, SecretScanInput } from './secret-scan.js'
export { ComprehensiveSecurityReview } from './comprehensive-security-verification.js'
export type { ComprehensiveSecurityFinding, ComprehensiveSecurityInput, ComprehensiveSecurityReport, SecurityEvidenceCheck } from './comprehensive-security-verification.js'
