/** Stage 04 package boundary. Runtime orchestration remains behind a mock-only seam. */
export { intersectCapabilities, intersectPaths, isPathWithin, isSafeWorkspacePath, pathsOverlap } from './capability-intersection.js'
export { DelegationGuard } from './delegation-guard.js'
export type { DelegationAllowDecision, DelegationArtifactHash, DelegationOptions, DelegationSnapshot } from './delegation-guard.js'
export { AgentFactory } from './agent-factory.js'
export type { AgentFactoryDecision, AgentFactoryOptions } from './agent-factory.js'
export { BudgetLedger } from './budget-ledger.js'
export type { BudgetLedgerRecordState, BudgetLedgerReservationState, BudgetLedgerState, BudgetOverrun, BudgetReservation, BudgetSnapshot } from './budget-ledger.js'
export { DurableBudgetLedger, WorkspaceBudgetLedgerStorage } from './durable-budget-ledger.js'
export type { BudgetLedgerStorage, DurableBudgetLedgerOptions } from './durable-budget-ledger.js'
export { TaskQueue } from './task-queue.js'
export type { TaskPriority } from './task-queue.js'
export { TaskScheduler, TaskSchedulerDisposedError } from './task-scheduler.js'
export type { TaskSchedulerOptions, TaskSchedulerSnapshot } from './task-scheduler.js'
export { PresetLoader } from './preset-loader.js'
export type { ExpertPreset } from './preset-loader.js'
export { RolePolicy } from './role-policy.js'
export { assertSafeWorkspacePath, isPathWithin as isCanonicalPathWithin, pathsOverlap as canonicalPathsOverlap } from './path-overlap.js'
export { OwnershipManager } from './ownership-manager.js'
export type { OwnedTask, OwnershipAcquireOptions, OwnershipLease, OwnershipLeaseSnapshot, OwnershipManagerOptions, OwnershipMode } from './ownership-manager.js'
export { SharedResource } from './shared-resource.js'
export type { SharedResourceLease, SharedResourceOptions, SharedResourceSnapshot } from './shared-resource.js'
export { ContextBuilder } from './context-builder.js'
export type { ApprovedArtifactExcerpt, ContextBuildInput, ContextBuilderOptions, ContextPacket } from './context-builder.js'
export { ContextBudgetError, ContextBudgetWindow, ContextCompactionError, ContextManager, FileContextCheckpointStore, MemoryContextCheckpointStore, PostgresContextCheckpointStore } from './context-manager.js'
export type { ContextBudgetWindowOptions, ContextBudgetWindowSnapshot, ContextCheckpoint, ContextCheckpointStore, ContextCompactionArtifact, ContextManagerOptions, ContextMessage, ContextMessageRole, ContextProjection, ContextSummarizer, ContextSummarizerInput, ContextSummary, ContextToolCallState, NativeCompactionProvider, NativeCompactionResult, PostgresCheckpointQueryPort } from './context-manager.js'
export { LongTaskExecutionSession, SharedLongTaskRunLease, ownershipPort } from './long-task-execution-session.js'
export type { LongTaskBudgetLedgerPort, LongTaskExecutionSessionOptions, LongTaskExecutionSnapshot, LongTaskOwnershipPort, LongTaskRunLeasePort, LongTaskToolResult } from './long-task-execution-session.js'
export { HandoffStore } from './handoff-store.js'
export type { DurableHandoff, HandoffStoreOptions, ParentAcknowledgementStatus } from './handoff-store.js'
export { ResultVerifier } from './result-verifier.js'
export type { ResultVerificationOptions, VerificationDecision } from './result-verifier.js'
export { AgentResultFormatError, decodeHarnessAgentResult } from './agent-result-decoder.js'
export type { HarnessResultDecoderInput } from './agent-result-decoder.js'
export { TeamRuntime } from './team-runtime.js'
export type { RuntimeExpertInput, TeamRuntimeCoordinator, TeamRuntimeOptions } from './team-runtime.js'
export { VerifiedAgentRuntimeBinding } from './verified-agent-runtime-binding.js'
export type { VerifiedAgentRuntime } from './verified-agent-runtime-binding.js'
